return {
	Lightning = {
		DisplayName = "Lightning",
		Damage = 20,
		DamagePerUpgrade = 10,
		MaxUpgradeLevel = 5,
		UpgradeCosts = {
			50,
			100,
			175,
			250,
			350,
		},
		Cooldown = 0.35,
		Range = 35,
		Radius = 5,
		AimAssistRadius = 4,
		DirectHitRadius = 2.75,
		AimAssistForwardBias = 0.35,
		ChainRange = 34,
		ChainTargetsPerUpgrade = 1,
		BoltSegments = 12,
		BranchCount = 6,
		BeamHeight = 1.2,
		KillKnockback = 82,
		KnockbackUpward = 34,
		KnockbackDuration = 0.16,
	},
	Meteor = {
		DisplayName = "Meteor",
		MaxUpgradeLevel = 5,
		UpgradeCosts = {
			150,
			225,
			325,
			450,
			650,
		},
		Cooldown = 5,
		HandCooldown = 2,
		Range = 95,
		ProjectileSpeed = 115,
		HandAimAssistRadius = 18,
		HandCastLevels = {
			[1] = {
				Damage = 40,
				Radius = 10,
				Scale = 0.12,
			},
			[2] = {
				Damage = 60,
				Radius = 12,
				Scale = 0.16,
			},
			[3] = {
				Damage = 80,
				Radius = 15,
				Scale = 0.22,
			},
		},
		AirStrikeLevels = {
			[4] = {
				Damage = 60,
				Radius = 40,
				Scale = 0.95,
			},
			[5] = {
				Damage = 60,
				Radius = 40,
				Scale = 1.15,
			},
		},
		AirStrikeHeight = 115,
		AirStrikeFallTime = 0.9,
		GroupSearchRadius = 40,
		FireDamage = 5,
		FireTickInterval = 1,
		FireDuration = 5,
		FireRadius = 40,
		ImpactLift = 1.5,
	},
	Tornado = {
		DisplayName = "Tornado",
		MaxUpgradeLevel = 5,
		UpgradeCosts = {
			100,
			175,
			275,
			400,
			575,
		},
		Cooldown = 7,
		Range = 85,
		Radius = 16,
		Damage = 10,
		DamagePerUpgrade = 3,
		TickInterval = 0.35,
		Duration = 4.2,
		Height = 34,
		ProjectileSpeed = 32,
		TrackingSpeed = 26,
		TrackingRange = 55,
		TrackingRetargetInterval = 0.35,
		PullStrength = 62,
		SwirlStrength = 44,
		LiftStrength = 24,
		HoldRadius = 5.5,
		ReleaseHorizontal = 72,
		ReleaseUpward = 38,
		ReleaseRagdollDuration = 1.25,
		VFXScale = 1,
	},
}
