return {
	BasicZombie = {
		Class = "Zombie",
		Subclass = "BasicZombie",
		DisplayName = "Zombie",
		AssetPath = {
			"ReplicatedStorage",
			"Assets",
			"Zombies",
			"BasicZombie",
			"Zombie",
		},
		Damage = 10,
		WalkSpeed = 12.5,
		AttackRange = 2.6,
		AttackCooldown = 1.25,
		AttackWindup = 0.25,
		AggroRange = math.huge,
		SpawnAnimationId = "rbxassetid://139677043780015",
		SpawnAnimationDuration = 2.2,
		FacingResponsiveness = 18,
		SurroundRadius = 2.25,
		MovementTick = 0.05,
		MoveLookaheadDistance = 6,
		GridSize = 5,
		RepathInterval = 0.25,
		MaxPathNodes = 900,
		PathNodeReachDistance = 3.5,
		MaxGroundStepHeight = 3.5,
		AgentRadius = 1.45,
		AgentHeight = 5,
		AgentCanClimb = true,
		PathWaypointSpacing = 3,
		PathCosts = {
			Danger = 4,
		},
		ObstacleFeelerDistance = 5,
		ObstacleAvoidanceWeight = 0.55,
		ObstacleCommitTime = 0.35,
		SeparationRadius = 3.4,
		SeparationWeight = 0.22,
		StuckCheckInterval = 0.45,
		StuckDistance = 0.7,
		StuckAvoidanceTime = 0.65,
		Appearance = {
			SkinColor = Color3.fromRGB(154, 210, 120),
			ShirtColor = Color3.fromRGB(116, 78, 49),
			PantsColor = Color3.fromRGB(93, 60, 38),
			EyeColor = Color3.fromRGB(25, 35, 20),
		},
		SpecialAttacks = {},
	},
}
