return {
	BasicZombie = {
		Class = "Zombie",
		Subclass = "BasicZombie",
		DisplayName = "Zombie",
		AssetPath = {
			"ReplicatedStorage",
			"Assets",
			"Zombies",
			"BasicZombie",
			"Zombie",
		},
		Damage = 10,
		WalkSpeed = 12.5,
		AttackRange = 2.6,
		AttackCooldown = 1.25,
		AttackWindup = 0.25,
		AggroRange = math.huge,
		SpawnAnimationId = "rbxassetid://139677043780015",
		SpawnAnimationDuration = 2.2,
		FacingResponsiveness = 18,
		SurroundRadius = 2.25,
		MovementTick = 0.05,
		MoveLookaheadDistance = 6,
		GridSize = 5,
		RepathInterval = 0.25,
		MaxPathNodes = 900,
		PathNodeReachDistance = 3.5,
		MaxGroundStepHeight = 3.5,
		AgentRadius = 1.45,
		AgentHeight = 5,
		AgentCanClimb = true,
		PathWaypointSpacing = 3,
		PathCosts = {
			Danger = 4,
		},
		ObstacleFeelerDistance = 5,
		ObstacleAvoidanceWeight = 0.55,
		ObstacleCommitTime = 0.35,
		SeparationRadius = 3.4,
		SeparationWeight = 0.22,
		StuckCheckInterval = 0.45,
		StuckDistance = 0.7,
		StuckAvoidanceTime = 0.65,
		Appearance = {
			SkinColor = Color3.fromRGB(154, 210, 120),
			ShirtColor = Color3.fromRGB(116, 78, 49),
			PantsColor = Color3.fromRGB(93, 60, 38),
			EyeColor = Color3.fromRGB(25, 35, 20),
		},
		SpecialAttacks = {},
	},
	Sprinter = {
		Class = "Zombie",
		Subclass = "Sprinter",
		DisplayName = "Sprinter",
		AssetPath = {
			"ReplicatedStorage",
			"Assets",
			"Zombies",
			"Sprinter",
			"Zombie",
		},
		Damage = 9,
		WalkSpeed = 17.5,
		AttackRange = 2.6,
		AttackCooldown = 1.1,
		AttackWindup = 0.2,
		AggroRange = math.huge,
		SpawnAnimationId = "rbxassetid://139677043780015",
		SpawnAnimationDuration = 1.7,
		FacingResponsiveness = 20,
		SurroundRadius = 1.8,
		MovementTick = 0.05,
		MoveLookaheadDistance = 7.4,
		GridSize = 5,
		RepathInterval = 0.22,
		MaxPathNodes = 900,
		PathNodeReachDistance = 3.5,
		MaxGroundStepHeight = 3.5,
		AgentRadius = 1.35,
		AgentHeight = 5,
		AgentCanClimb = true,
		PathWaypointSpacing = 3,
		PathCosts = {
			Danger = 4,
		},
		ObstacleFeelerDistance = 5,
		ObstacleAvoidanceWeight = 0.55,
		ObstacleCommitTime = 0.3,
		SeparationRadius = 3.2,
		SeparationWeight = 0.24,
		StuckCheckInterval = 0.42,
		StuckDistance = 0.7,
		StuckAvoidanceTime = 0.62,
		Appearance = {
			SkinColor = Color3.fromRGB(123, 224, 109),
			ShirtColor = Color3.fromRGB(99, 69, 45),
			PantsColor = Color3.fromRGB(74, 49, 31),
			EyeColor = Color3.fromRGB(25, 35, 20),
		},
		SpecialAttacks = {},
	},
	Tank = {
		Class = "Zombie",
		Subclass = "Tank",
		DisplayName = "Tank",
		AssetPath = {
			"ReplicatedStorage",
			"Assets",
			"Zombies",
			"Tank",
			"Zombie",
		},
		Damage = 16,
		WalkSpeed = 8.4,
		AttackRange = 3.1,
		AttackCooldown = 1.7,
		AttackWindup = 0.3,
		AggroRange = math.huge,
		SpawnAnimationId = "rbxassetid://139677043780015",
		SpawnAnimationDuration = 2.3,
		FacingResponsiveness = 12,
		SurroundRadius = 3.2,
		MovementTick = 0.06,
		MoveLookaheadDistance = 5.2,
		GridSize = 5,
		RepathInterval = 0.3,
		MaxPathNodes = 900,
		PathNodeReachDistance = 3.5,
		MaxGroundStepHeight = 3.5,
		AgentRadius = 1.65,
		AgentHeight = 5.6,
		AgentCanClimb = true,
		PathWaypointSpacing = 3,
		PathCosts = {
			Danger = 4,
		},
		ObstacleFeelerDistance = 5.6,
		ObstacleAvoidanceWeight = 0.6,
		ObstacleCommitTime = 0.38,
		SeparationRadius = 3.8,
		SeparationWeight = 0.2,
		StuckCheckInterval = 0.48,
		StuckDistance = 0.7,
		StuckAvoidanceTime = 0.7,
		Appearance = {
			SkinColor = Color3.fromRGB(137, 199, 104),
			ShirtColor = Color3.fromRGB(94, 73, 52),
			PantsColor = Color3.fromRGB(78, 58, 40),
			EyeColor = Color3.fromRGB(25, 35, 20),
		},
		SpecialAttacks = {},
	},
	LightningMinion = {
		Class = "Zombie",
		Subclass = "LightningMinion",
		DisplayName = "Spark Zombie",
		AssetPath = {
			"ReplicatedStorage",
			"Assets",
			"Zombies",
			"BasicZombie",
			"Zombie",
		},
		Damage = 8,
		WalkSpeed = 18.5,
		AttackRange = 2.4,
		AttackCooldown = 0.9,
		AttackWindup = 0.16,
		AggroRange = math.huge,
		SpawnAnimationId = "rbxassetid://139677043780015",
		SpawnAnimationDuration = 0.9,
		FacingResponsiveness = 24,
		SurroundRadius = 1.7,
		MovementTick = 0.045,
		MoveLookaheadDistance = 7.8,
		GridSize = 5,
		RepathInterval = 0.2,
		MaxPathNodes = 900,
		PathNodeReachDistance = 3.5,
		MaxGroundStepHeight = 3.5,
		ObstacleFeelerDistance = 5,
		ObstacleAvoidanceWeight = 0.55,
		ObstacleCommitTime = 0.28,
		SeparationRadius = 3,
		SeparationWeight = 0.25,
		StuckCheckInterval = 0.4,
		StuckDistance = 0.65,
		StuckAvoidanceTime = 0.55,
		Appearance = {
			SkinColor = Color3.fromRGB(98, 215, 255),
			ShirtColor = Color3.fromRGB(25, 62, 132),
			PantsColor = Color3.fromRGB(18, 34, 70),
			EyeColor = Color3.fromRGB(180, 245, 255),
		},
		SpecialAttacks = {},
	},
	LightningBoss = {
		Class = "Zombie",
		Subclass = "LightningBoss",
		DisplayName = "Storm Bringer",
		AssetPath = {
			"ReplicatedStorage",
			"Assets",
			"Bosses",
			"LightningBoss",
			"LightningBossZombie",
		},
		Damage = 20,
		WalkSpeed = 8.6,
		AttackRange = 4.2,
		AttackCooldown = 1.8,
		AttackWindup = 0.35,
		AggroRange = math.huge,
		SpawnAnimationId = "rbxassetid://139677043780015",
		SpawnAnimationDuration = 2.4,
		IdleAnimationId = "rbxassetid://116307374668513",
		FacingResponsiveness = 10,
		SurroundRadius = 5.5,
		MovementTick = 0.06,
		MoveLookaheadDistance = 5,
		GridSize = 5,
		RepathInterval = 0.32,
		MaxPathNodes = 900,
		PathNodeReachDistance = 4,
		MaxGroundStepHeight = 3.5,
		ObstacleFeelerDistance = 6,
		ObstacleAvoidanceWeight = 0.6,
		ObstacleCommitTime = 0.4,
		SeparationRadius = 6,
		SeparationWeight = 0.12,
		StuckCheckInterval = 0.5,
		StuckDistance = 0.75,
		StuckAvoidanceTime = 0.75,
		KiteMinRange = 22,
		KiteIdealRange = 34,
		KiteMaxRange = 46,
		KiteOrbitStep = 0.42,
		Appearance = {
			SkinColor = Color3.fromRGB(83, 194, 255),
			ShirtColor = Color3.fromRGB(20, 52, 124),
			PantsColor = Color3.fromRGB(10, 24, 64),
			EyeColor = Color3.fromRGB(220, 255, 255),
		},
		SpecialAttacks = {
			LightningWarningTime = 0.9,
			LightningRadius = 9.5,
			LightningDamage = 44,
			LightningCooldown = 2.65,
			LightningExtraStrikeChance = 0.45,
			SummonCooldown = 6.5,
			SummonCount = 5,
		},
	},
}
